
"""
Add your CosmosDB NoSQL database schema in this file

For example:

type schedule @model {
  id: ID
  data: String,
  workers: [
    workderId:String,
    name:String,
    shift
  ]
}

"""

// graphql/schema.gql
type Worker {
    workerId: String
    name: String
    shift: String
}

type Schedule {
    id: String
    date: String
    workers: [Worker]
}

type Query {
    workers: [Schedule]
}
